spring:
    application:
        name: obsidian-second-brain
    profiles:
        active: local
    ai: 
        google: 
            genai: 
                api-key: ${GEMINI_API_KEY}
                chat:
                    model: gemini-2.5-flash
                    response-mime-type: application/json
                    temperature: 0.5
                embedding:
                    api-key: ${GEMINI_API_KEY}
                    text:
                        task-type: RETRIEVAL_DOCUMENT 
        model:
            chat: google-genai
        mcp:
            server:
                name: obsidian-knowledge-engine
                version: 1.0.0
                stdio: true
                type: ASYNC
                annotation-scanner:
                    enabled: true 

    
         

# obsidian:
  #  vault-path: ${obsidian.vault-path}




